name: Autonomous Testing Agent

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours

env:
  NODE_VERSION: '18'

jobs:
  autonomous-agent-health:
    name: Test Autonomous Agents
    runs-on: ubuntu-latest
    continue-on-error: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Prisma client
        run: npm run db:generate
        
      - name: Run Autonomous Testing Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: npm run test:autonomous
        
      - name: Upload agent test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: autonomous-test-report
          path: autonomous-testing-report.md

  agent-startup-validation:
    name: Validate Agent Startup
    runs-on: ubuntu-latest
    continue-on-error: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate Prisma client
        run: npm run db:generate
        
      - name: Test Agent Startup (No API Key)
        run: node scripts/autonomous-testing-agent.js --test-startup
        
      - name: Validate OpenAI Integration
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scripts/autonomous-testing-agent.js --test-openai

  health-check:
    name: System Health Check
    runs-on: ubuntu-latest
    continue-on-error: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        
      - name: Start services in background
        run: |
          npm run start &
          sleep 30
          
      - name: Health check endpoints
        run: npm run health-check
        
      - name: Stop services
        run: pkill -f "npm run start" || true